// action creators - piece of code that will generate actual action with will be dispatched to reducer
import axios from 'axios';
import { FETCH_USER } from './types';

// if we return a function from action creator,
//  redux-thunk will automatically call that function and pass in 'dispatch' function as an argument to that called function
export const fetchUser = () => async dispatch => {
  const res = await axios.get('/api/current_user');
  dispatch({
    type: FETCH_USER,
    payLoad: res.data
  });
};

// Once sourceID is generated by stripe-react-plugin, send it back to back end for furthur processing (creating charge)
export const handleToken = token => async dispatch => {
  const res = await axios.post('/api/stripe', token);
  dispatch({
    type: FETCH_USER,
    payLoad: res.data
  });
};
